Repository rasikaghadge/AI-Automated-Interview-Platform, pull requests merged in 2023-10, with the labels that each got.

#35 Add google authentication for users
  schema.json
  server/controllers/token.js
  server/controllers/user.js
  server/helper/passport.js
  server/index.js
  server/middleware/auth.js
  server/models/Meeting.js
  server/package-lock.json
  server/package.json
  server/routes/profile.js
  server/routes/userRoutes.js
  server/views/pages/auth.ejs
  server/views/pages/success.ejs
Labels: enhancement, under development

#36 Changes in homepage acc. to user role
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/actions/auth.js
  client/src/api/index.js
  client/src/components/Hero/Hero.js
  client/src/components/Home/Home.js
  client/src/components/Homepage/Homepage.js
  client/src/components/Login/Login.js
  client/src/components/NavBar/NavBar.js
  client/yarn.lock
  server/controllers/profile.js
  server/controllers/token.js
  server/controllers/user.js
  server/models/ProfileModel.js
  server/models/userModel.js
  server/package-lock.json
  server/package.json
Labels: enhancement, under development, do not merge

#37 add prompts and meet scheduling api
  server/controllers/meetings.js
  server/controllers/scheduler.js
  server/controllers/user.js
  server/helper/prompts.js
  server/models/Meeting.js
  server/routes/meet.js
  server/routes/userRoutes.js
Labels: review required before merge
