Repository rasikaghadge/AI-Automated-Interview-Platform, pull requests merged in 2024-01, with the labels that each got.

#90 backend + workflow + frontend fix
  .github/workflows/docker-publish.yml
  README.md
  client/src/components/SeeScheduledInterviews/SeeScheduledInterviews.js
  server/controllers/interviews.js
  server/controllers/profile.js
Labels: enhancement, merge me

#97 Routed join interview button to videosdk meeting page with Room id and candidate name
  client/src/components/MeetingDetailsScreen.js
  client/src/components/SeeScheduledInterviews/SeeScheduledInterviews.js
  client/src/components/VideosdkMeeting/VideosdkMeeting.js
  client/src/components/screens/JoiningScreen.js
  server/controllers/interviews.js
Labels: enhancement, review required before merge, merge me

#94 [Migration] migrating server code from javascript to typescript
  docker-compose.yml
  server/controllers/user.js
  server/documents/email.js
  server/index.js
  server/models/Interview.js
  server/models/ProfileModel.js
  server/models/userModel.js
  server/package-lock.json
  server/package.json
  server/src/controllers/interviews.ts
  server/src/controllers/profile.ts
  server/src/controllers/token.ts
  server/src/controllers/user.ts
  server/src/controllers/videosdk.ts
  server/src/documents/email.ts
  server/src/helper/authHelper.ts
  server/src/helper/prompts.ts
  server/src/helper/videosdkHelper.ts
  server/src/index.ts
  server/src/middleware/auth.ts
  server/src/models/Interview.ts
  server/src/models/ProfileModel.ts
  server/src/models/userModel.ts
  server/src/routes/interviews.ts
  server/src/routes/profile.ts
  server/src/routes/userRoutes.ts
  server/src/schemas/InterviewType.ts
  server/src/schemas/ProfileType.ts
  server/src/schemas/UserType.ts
  server/tsconfig.json
Labels: review required before merge, merge me

#105 Removed videosdk, created custom interview page
  client/src/App.js
  client/src/components/ConfirmBox.js
  client/src/components/Icons.js
  client/src/components/Interview/Interview.js
  client/src/components/Interview/Interview.module.css
  client/src/components/MeetingDetailsScreen.js
  client/src/components/ParticipantGrid.js
  client/src/components/ParticipantView.js
  client/src/components/PresenterView.js
  client/src/components/SeeScheduledInterviews/SeeScheduledInterviews.js
  client/src/components/SettingDialogueBox.js
  client/src/components/VideosdkMeeting/MeetingAppContextDef.js
  client/src/components/VideosdkMeeting/VideosdkMeeting.css
  client/src/components/VideosdkMeeting/VideosdkMeeting.js
  client/src/components/VideosdkMeeting/tailwind_build.css
  client/src/components/buttons/MobileIconButton.js
  client/src/components/buttons/OutlineIconTextButton.js
  client/src/components/buttons/OutlinedButton.js
  client/src/components/screens/JoiningScreen.js
  client/src/components/screens/LeaveScreen.js
  client/src/components/screens/WaitingToJoinScreen.js
  client/src/hooks/useIsMobile.js
  client/src/hooks/useIsRecording.js
  client/src/hooks/useIsTab.js
  client/src/hooks/useMediaStream.js
  client/src/hooks/useWindowSize.js
  client/src/icons/Bottombar/ChatIcon.js
  client/src/icons/Bottombar/EndIcon.js
  client/src/icons/Bottombar/MicOffIcon.js
  client/src/icons/Bottombar/MicOnIcon.js
  client/src/icons/Bottombar/ParticipantsIcon.js
  client/src/icons/Bottombar/PipIcon.js
  client/src/icons/Bottombar/RaiseHandIcon.js
  client/src/icons/Bottombar/RecordingIcon.js
  client/src/icons/Bottombar/ScreenShareIcon.js
  client/src/icons/Bottombar/WebcamOffIcon.js
  client/src/icons/Bottombar/WebcamOnIcon.js
  client/src/icons/MicOffIcon.js
  client/src/icons/MicOffSmallIcon.js
  client/src/icons/NetworkIcon.js
  client/src/icons/ParticipantTabPanel/MicOffIcon.js
  client/src/icons/ParticipantTabPanel/MicOnIcon.js
  client/src/icons/ParticipantTabPanel/RaiseHand.js
  client/src/icons/ParticipantTabPanel/VideoCamOffIcon.js
  client/src/icons/ParticipantTabPanel/VideoCamOnIcon.js
  client/src/icons/ScreenShareIcon.js
  client/src/icons/SpeakerIcon.js
  client/src/icons/WebcamOffIcon.js
  client/src/meeting/MeetingContainer.js
  client/src/meeting/components/BottomBar.js
  client/src/meeting/components/ParticipantView.js
  client/src/static/animations/join_meeting.json
  client/src/static/animations/recording-blink.json
  client/src/utils/common.js
  client/src/utils/helper.js
  client/src/utils/utils.js
Labels: review required before merge, merge me

#110 Remove videosdk support
  server/middleware/auth.js
  server/src/controllers/interviews.ts
  server/src/controllers/token.ts
  server/src/helper/videosdkHelper.ts
  server/src/models/Interview.ts
  server/src/schemas/InterviewType.ts
  server/src/tsconfig.json
Labels: merge me
