Repository rasikaghadge/AI-Automated-Interview-Platform, pull requests merged in 2024-02, with the labels that each got.

#112 Send audio data to AI
  client/src/components/Interview/FirstQuestions.js
  client/src/components/Interview/Interview.js
  client/src/components/SeeScheduledInterviews/SeeScheduledInterviews.js
Labels: do not merge

#114 Backend with Fastapi and supabase
  README.md
  ai-interviewer/app/api/deps.py
  ai-interviewer/app/api/endpoints/meetings.py
  ai-interviewer/app/api/endpoints/users.py
  ai-interviewer/app/core/config.py
  ai-interviewer/app/main.py
  ai-interviewer/app/schemas/requests.py
  ai-interviewer/app/schemas/responses.py
  ai-interviewer/requirements.txt
Labels: enhancement, merge me

#117 remove videosdk support
  .github/workflows/greetings.yml
  .github/workflows/label.yml
  .github/workflows/manual.yml
  client/src/actions/invoiceActions.js
  client/src/api/index.js
  client/src/clients.json
  client/src/currencies.json
  client/src/index.js
  client/src/reducers/clients.js
  client/src/reducers/index.js
  client/src/reducers/invoices.js
  client/src/store.js
  server/src/controllers/interviews.ts
  server/src/controllers/profile.ts
  server/src/controllers/user.ts
  server/src/controllers/videosdk.ts
  server/src/documents/email.ts
  server/src/index.ts
  server/src/middleware/auth.ts
  server/src/routes/interviews.ts
Labels: review required before merge, merge me

#118 Pradnya - modified end interview code and changed interview page layout
  .github/workflows/docker-backend-fastapi.yml
  ai-interviewer/.env.example
  ai-interviewer/.gitignore
  ai-interviewer/Dockerfile
  ai-interviewer/alembic.ini
  ai-interviewer/alembic/README
  ai-interviewer/alembic/env.py
  ai-interviewer/alembic/script.py.mako
  ai-interviewer/alembic/versions/2023020440_init_user_model_07c71f4389b6.py
  ai-interviewer/app/__init__.py
  ai-interviewer/app/api/__init__.py
  ai-interviewer/app/api/api.py
  ai-interviewer/app/api/deps.py
  ai-interviewer/app/api/endpoints/__init__.py
  ai-interviewer/app/api/endpoints/meetings.py
  ai-interviewer/app/api/endpoints/users.py
  ai-interviewer/app/conftest.py
  ai-interviewer/app/core/__init__.py
  ai-interviewer/app/core/config.py
  ai-interviewer/app/core/security.py
  ai-interviewer/app/core/session.py
  ai-interviewer/app/initial_data.py
  ai-interviewer/app/main.py
  ai-interviewer/app/models.py
  ai-interviewer/app/schemas/__init__.py
  ai-interviewer/app/schemas/requests.py
  ai-interviewer/app/schemas/responses.py
  ai-interviewer/app/tests/__init__.py
  ai-interviewer/app/tests/conftest.py
  ai-interviewer/app/tests/test_auth.py
  ai-interviewer/app/tests/test_users.py
  ai-interviewer/docker-compose.dev.yml
  ai-interviewer/docker-compose.yml
  ai-interviewer/init.sh
  ai-interviewer/requirements-dev.txt
  ai-interviewer/requirements.txt
  ai-interviewer/setup.cfg
  client/src/App.js
  client/src/components/Interview/Interview.js
  client/src/components/Interview/Interview.module.css
  client/src/components/Interview/interview_img.jpg
  client/src/components/Schedule/Schedule.js
  server/src/routes/interviews.ts
Labels: fix conflicts before merge

#123 Timer to answer question
  client/src/components/Interview/Interview.js
  client/src/components/Interview/Interview.module.css
Labels: do not merge

#124 Change interview status when interview is completed or ended
  client/src/actions/constants.js
  client/src/actions/interviews.js
  client/src/api/index.js
  client/src/components/Interview/Interview.js
  client/src/components/SeeScheduledInterviews/SeeScheduledInterviews.js
  server/src/controllers/interviews.ts
  server/src/routes/interviews.ts
Labels: do not merge

#127 Add routes to update meeting details
  .github/workflows/interviews.yml
  server/Dockerfile
  server/src/controllers/interviews.ts
  server/src/routes/interviews.ts
  server/tsconfig.json
Labels: merge me

#134 Add new image in homepage
  client/src/Assets/banner2.png
  client/src/components/Home/Home.js
Labels: merge me
