Repository rasikaghadge/AI-Automated-Interview-Platform, pull requests merged in 2024-04, with the labels that each got.

#162 add topic and required skills
  client/src/components/Schedule/Schedule.js
Labels: merge me

#167 add two additional field in Interview schema
  server/src/controllers/interviews.ts
  server/src/models/Interview.ts
  server/src/schemas/InterviewType.ts
Labels: merge me

#168 add new route to get score
  server/package-lock.json
  server/package.json
  server/src/controllers/interviews.ts
  server/src/models/ChatHistory.ts
  server/src/routes/interviews.ts
  server/src/schemas/ChatHistory.ts
Labels: merge me

#170 Changes for compatibility with new django code
  client/src/actions/profile.js
  client/src/api/index.js
  client/src/components/Interview/Interview.js
  client/src/components/UserDetails/UserDetails.js
Labels: merge me

#173 fix error. reading json again.
  client/src/components/Interview/Interview.js
Labels: merge me

#174 Fix bugs in frontend
  .github/workflows/interviews.yml
  client/src/components/Interview/Interview.js
  server/src/models/Interview.ts
Labels: review required before merge, merge me

#179 frontend fixes
  client/src/actions/auth.js
  client/src/components/SeeScheduledInterviews/SeeScheduledInterviews.js
  client/src/components/SeeScheduledInterviews/UserProfileDetails.js
Labels: merge me, merge after testing
